### ISSUE TITLE
Can we tag new version?

### ISSUE THREAD

**Issue by paluh** [rgrempel/purescript-int-53#16]
I know that previous merge has removed old generic support (which is discussed a bit further under PR: https://github.com/rgrempel/purescript-int-53/pull/15).

Do you consider tagging and publishing new version without generic support for now?

I don't want to push anything but to be honest missing official release of int53 blocks our other libraries (like redis client) releases ;-)

**Comment by rgrempel** [comment]
My apologies -- I should have done that already! I shall do it now.

**Comment by rgrempel** [comment]
I have tagged version 4.0.0 and published the docs.

**Comment by paluh** [comment]
Thanks!
