### ISSUE TITLE
Degree?

### ISSUE THREAD

**Issue by clayrat** [rgrempel/purescript-int-53#7]
For consistency, `degree` for Ints in `Prelude` is defined via `abs`, whereas here you reuse the version for Numbers, which is simply a constant `1`.

I'm actually wondering why `degree` is even required, since (AFAIK) its' only usage is during the proof that a generalized GCD algorithm exists for a chosen ring.

**Comment by clayrat** [comment]
Ah, I was wrong, it is actually used in the division algorithm itself, e.g., https://en.wikipedia.org/wiki/Polynomial_greatest_common_divisor#Euclidean_division

However, we need not to redefine the division algorithm, as we have to provide `div` and `mod` separately. So it seems `degree` is still extraneous.

**Comment by rgrempel** [comment]
To be honest, I had not really understood what `degree` was intended to do -- I will review when I get a chance in light of this discussion:

https://github.com/purescript/purescript-prelude/issues/99

**Comment by garyb** [comment]
Regardless of the issues brought up in that description, `degree` for integers is definitely `abs`. See the [examples on Wikipedia](https://en.wikipedia.org/wiki/Euclidean_domain#Examples) for instance:

- ℤ, the ring of integers. Define f(n) = |n|, the absolute value of n.

A constant degree of 1 suggests the type is actually a `Field`, meaning ``∀ x y. x `mod` y = 0``.
