### ISSUE TITLE
FYI: 2.1.0 => 2.1.1 upgrade

### ISSUE THREAD

**Issue by damncabbage** [rgrempel/purescript-int-53#9]
I just want to begin by thanking you for your work writing `purescript-int-53`. 😄 

This issue is more advisory than anything, but the 2.1.0 to 2.1.1 patch upgrade included your bumping versions of Prelude and other libraries which, due to the flat resolution that PureScript/Bower uses, resulted in a rippling upgrade of everything in my app (… which broke everything).

I might suggest a major version bump in future, much like the other standard libraries did when they bumped their own dependencies.

In any case, thanks again; feel free to close this when you see it.

**Comment by rgrempel** [comment]
Ah, my apologies ... I guess I was thinking of the semantic versioning of my own API, without considering the ripple effects.

I suppose one needs to do a major version bump whenever a dependency does a major version bump, even if my own code is unchanged? That seems awkward, but I guess it's necessary.
